server:
  port: 8080

application:
  module:
    obesidade: http://localhost:8081
    sedentarismo: http://localhost:8082
    tabagismo: http://localhost:8083
    pressaosistolica: http://localhost:8084
